server:
  port: 8550
# DataSource Config
spring:
  springdoc:
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
    api-docs.path: /api-docs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pos_springboot_vue_3?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: LP2416jc3103
#  security:
#    user:
#      name: user
#      password: 111111
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
possystem:
  jwt:
    header: Authorization
    expire: 86400 #1 day
    secret: ji8n3439n439n43ld9ne9343fdfer49h # 秘钥
swagger:
  enabled: true